# -*- coding: utf-8 -*-
"""Binary Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XG-43eYdlZ37_KoLcFPuv0-bxBStuSIW
"""

e!pip install nltk

pip install wordcloud

import re
import json
import nltk
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

nltk.download('punkt')  # for tokenization

# Sample multilingual text
text_samples = [
    {"language": "Marathi", "text": "आज मला खपू आनदं होत आहे."},
    {"language": "Hindi", "text": "आज मझेेु बहेुत खशी ेुु हो रही है।"},
    {"language": "Gujarati", "text": "આજે મને ખુબ આનંદ થઈ રહ્યો છે.."}
]

# Step 1: Preprocessing
def preprocess_text(text):
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    return text.strip()

def tokenize_text(text):
    return nltk.word_tokenize(text)

# Store processed data
language_tokens = {"Marathi": [], "Hindi": [], "Gujarati": []}
dataset = []

for sample in text_samples:
    lang = sample["language"]
    original = sample["text"]
    cleaned = preprocess_text(original)
    tokens = tokenize_text(cleaned)

    token_str = ' '.join(tokens)
    language_tokens[lang].extend(tokens)

    dataset.append({
        "language": lang,
        "original_text": original,
        "tokenized_text": token_str
    })

# Step 3: Export to CSV and JSON
df = pd.DataFrame(dataset)
df.to_csv("multilingual_dataset.csv", index=False)

with open("multilingual_dataset.json", "w", encoding='utf-8') as f:
    json.dump(dataset, f, ensure_ascii=False, indent=4)

print("✅ Data exported to multilingual_dataset.csv and multilingual_dataset.json")

# Step 4: Generate Word Clouds
for lang, tokens in language_tokens.items():
    wc = WordCloud(font_path='NotoSansDevanagari-Regular.ttf', background_color='white', width=800, height=400)
    wc.generate(' '.join(tokens))
    plt.figure(figsize=(8, 4))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.title(f'{lang} Word Cloud', fontsize=16)
    plt.tight_layout()
    plt.show()